1.jpg:  
  caption: NE2
  alt: ALT one dot jpeg
2.jpg:  
  caption: NE3
  alt: ALT two dot jpeg
3.jpg:  
  caption: Selected Network Studies, relesead by NUKFM
  alt: ALT three dot jpeg
4.jpg:  
  caption: Flash Demons, released by MILLE PLATEAUX
  alt: ALT four dot jpeg