Plane-of-Theseus-1.jpg:  
  caption: Christine Meyer and Anita Nguyen, MA Visuelle Kommunikation, Weisensee
  alt: A website which says 'Crisis Control, the Customers are waiting'
Plane-of-Theseus-5.jpg: 
  caption: Ezequiel Hyon, MA Visuelle Kommunikation, Weisensee
  alt: Black and white, mri-style scans of the components of an aircraft
Plane-of-Theseus-3.jpg:  
  caption: Leon Schöler, MA Visuelle Kommunikation, Weisensee
  alt: An aircraft flying through dollar signs and oil barrels