Never-stop-stopping-1.jpg:
  caption: Amala Antony and Huan Ziqi
  alt: ALT Amala Antony and Huan Ziqi
Never-stop-stopping-2.jpg:
  caption: Paloma Moniz, Ricardo Gonçalves and Roxanne Zeiher
  alt: ALT Paloma Moniz, Ricardo Gonçalves and Roxanne Zeiher
Never-stop-stopping-3.jpg:
  caption: Paloma Moniz, Ricardo Gonçalves and Roxanne Zeiher
  alt: ALT Paloma Moniz, Ricardo Gonçalves and Roxanne Zeiher
Never-stop-stopping-4.jpg:
  caption: Qiong Zhao and Xinyi Wang
  alt: ALT Qiong Zhao and Xinyi Wang
Never-stop-stopping-5.jpg:
  caption: Source unknown
  alt: ALT Source unknown