Never-stop-stopping-1.jpg:
  caption: Amala Antony and Huan Ziqi, MA Graphic Media Design, LCC
  alt: ALT Amala Antony and Huan Ziqi, MA Graphic Media Design, LCC
Never-stop-stopping-2.jpg:
  caption: Paloma Moniz, Ricardo Gonçalves, Roxanne Zeiher, MA Graphic Media Design, LCC
  alt: ALT Paloma Moniz, Ricardo Gonçalves, Roxanne Zeiher, MA Graphic Media Design, LCC
Never-stop-stopping-3.jpg:
  caption: Paloma Moniz, Ricardo Gonçalves, Roxanne Zeiher, MA Graphic Media Design, LCC
  alt: ALT Paloma Moniz, Ricardo Gonçalves, Roxanne Zeiher, MA Graphic Media Design, LCC
Never-stop-stopping-4.jpg:
  caption: Qiong Zhao and Xinyi Wang, MA Graphic Media Design, LCC
  alt: ALT Qiong Zhao and Xinyi Wang, MA Graphic Media Design, LCC
Never-stop-stopping-5.jpg:
  caption: Source unknown
  alt: ALT Source unknown