1.jpg:  
  caption: Christine Meyer and Anita Nguyen, MA Visuelle Kommunikation, Weisensee
  alt: ALT Christine Meyer and Anita Nguyen, MA Visuelle Kommunikation, Weisensee
2.jpg: 
  caption: Ezequiel Hyon, MA Visuelle Kommunikation, Weisensee
  alt: ALT Ezequiel Hyon, MA Visuelle Kommunikation, Weisensee
4.jpg:  
  caption: Leon Schöler, MA Visuelle Kommunikation, Weisensee
  alt: ALT Leon Schöler, MA Visuelle Kommunikation, Weisensee
5.jpg:
  caption: Jason Yang, MA Moving Image, Ravensbourne University London
  alt: ALT Jason Yang, MA Moving Image, Ravensbourne University London
6.png:  
  caption: 
  alt: ALT six dot png